server:
  port: ${SERVER_PORT:30010}

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      jdbc-url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3307}/alarm
      username: dbuser
      password: dbpass
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

source:
  mariadb:
    host: ${CDC_SOURCE_HOST:192.168.0.56}
    port: ${CDC_SOURCE_PORT:3337}
    database: ${CDC_SOURCE_DATABASE:ecopeace}
    username: ${CDC_SOURCE_USER:dbuser}
    password: ${CDC_SOURCE_PASSWORD:dbpass}
    useSSL: false
    sslMode: DISABLED

  sfp:
    portal:
      url: ${SYNC_PORTAL_URL:http://misillan.sfp.nextorm.com}
      id: ${SYNC_PORTAL_ID:admin}
      password: ${SYNC_PORTAL_PASSWORD:admin}

  eqms:
    portal:
      url: ${SYNC_EQMS_URL:http://misillan.nextorm.com}
      id: ${SYNC_EQMS_ID:sffa}
      password: ${SYNC_EQMS_PASSWORD:admin}

cdc:
  enabled: ${CDC_ENABLED:true}
  data-dir: ${CDC_DATA_DIR:/cdc-data}

alarm:
  interval-seconds: ${ALARM_INTERVAL_SECONDS:60}