services:
  misillan-alarm-db:
    image: mariadb:10.6
    container_name: misillan-alarm-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: qwerqwer123
      MYSQL_DATABASE: alarm
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
      - --lower_case_table_names=1
      - --max_allowed_packet=104857600
    volumes:
      - ./db_data:/var/lib/mysql

